.\" Manpage of xwinmo/v0.1.0.2
.\" written with GNU Emacs/v24.3.1 and markdown-mode/v1.8.1
.\" generated with Ronn/v0.7.3
.
.TH "XWINMO" "1" "2014-02-17" "0.1.0.2" "User Manual"
.
.SH "NAME"
\fBxwinmo\fR \- move and size X windows
.
.SH "SYNOPSIS"
xwinmo (\-|\-F|\-h|\-v) [\-wx|\-wy|\-ww|\-wh] (\-c|\-f|\-H|\-M|\-m|\-U|\-s)
.
.SH "REQUIREMENT"
GNU bash, wmctrl, xprop, xwinpp
.
.SH "DESCRIPTION"
\fBxwinmo\fR is a simple bash shell script, that wraps up some \fBwmctrl\fR actions to provide processing of more than one x window\. Therefore, \fBxwinmo\fR is used in combination with \fBxwinpp\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-\fR
Get output from \fBxwinpp\fR by reading from standard input; \fB\-\fR must be the first argument\.
.
.TP
\fB\-F\fR, \fB\-file\fR \fIFILE\fR
Obtain output of \fBxwinpp\fR from \fIFILE\fR, not from standard input\.
.
.TP
\fB\-wx\fR, \fB\-workarea\-x\fR \fIPX\fR
Specify the left edge of the workarea\.
.
.TP
\fB\-wy\fR, \fB\-workarea\-y\fR \fIPX\fR
Specify the top edge of the workarea\.
.
.TP
\fB\-ww\fR, \fB\-workarea\-width\fR \fIPX\fR
Specify the \fIWIDTH\fR of the workarea\.
.
.TP
\fB\-wh\fR, \fB\-workarea\-height\fR \fIPX\fR
Specify the \fIHEIGHT\fR of the workarea\.
.
.TP
\fB\-h\fR, \fB\-help\fR
Display a short help\.
.
.TP
\fB\-v\fR, \fB\-version\fR
Print current version of \fBxwinmo\fR\.
.
.SH "SUBCOMMANDS"
.
.SS "ACTIONS"
.
.TP
\fB\-c\fR, \fB\-close\fR
Close windows gracefully\.
.
.TP
\fB\-H\fR, \fB\-hide\fR
Add window property \fIhidden\fR\.
.
.TP
\fB\-U\fR, \fB\-unhide\fR
Remove window property \fIhidden\fR\.
.
.TP
\fB\-f\fR, \fB\-focus\fR
Switch to the desktop containing the windows, raise the windows, and give them focus\. At the end, focus the active window again\.
.
.TP
\fB\-M\fR, \fB\-move\-to\-desk\fR
Tell \fBxwinmo\fR to move windows to another desktop\. Specify this action with options \fB\-D\fR and \fB\-W\fR\.
.
.TP
\fB\-s\fR, \fB\-size\fR
Tell \fBxwinmo\fR to size windows\. The sizing is specified by options \fB\-e\fR, \fB\-R\fR, \fB\-g\fR and \fB\-V\fR\.
.
.TP
\fB\-m\fR, \fB\-move\fR
Tell \fBxwinmo\fR to move windows\. The moving is specified by options \fB\-e\fR, \fB\-R\fR, \fB\-g\fR, \fB\-d\fR and \fB\-V\fR\.
.
.SS "OPTIONS"
.
.TP
\fB\-D\fR, \fB\-desk\fR \fIDESK\fR
Move windows to desktop \fIDESK\fR\.
.
.TP
\fB\-e\fR, \fB\-entity\fR \fIENT\fR
Specify the entity of actions \fB\-m\fR and \fB\-s\fR\.
.
.TP
\fB\-R\fR, \fB\-reference\fR \fIREF\fR
Used with action \fB\-m\fR and \fB\-s\fR\. If entity is \fBpro\fR, specify the reference\.
.
.TP
\fB\-g\fR, \fB\-geo\fR \fIGEO\fR
Specify the geometry of actions \fB\-m\fR and \fB\-s\fR\.
.
.TP
\fB\-d\fR, \fB\-direction\fR \fIDIREC\fR
Used with action \fB\-m\fR and \fBwindow\fR as reference\.
.
.TP
\fB\-V\fR, \fB\-active\fR
Tell \fBxwinmo\fR to perform \fB\-m\fR and \fB\-s\fR on active window\.
.
.TP
\fB\-W\fR, \fB\-switch\fR
Used with action \fB\-M\fR to switch to the desktop after moving\.
.
.SH "ARGUMENTS"
.
.TP
\fIFILE\fR
File may be a regular file or a named pipe\.
.
.TP
\fIPX\fR
Pixel size specified by an integer\.
.
.TP
\fIDESK\fR
Desktop number specified by an integer or \fBcurr\fR\.
.
.TP
\fIENT\fR
Can be \fBpx\fR or \fBpro\fR, what means \fBpixel\fR resp\. \fBprocent\fR\.
.
.TP
\fIREF\fR
Can be \fBwindow\fR or \fBworkarea\fR\.
.
.TP
\fIDIREC\fR
Can be \fBnorth\fR, \fBeast\fR, \fBsouth\fR or \fBwest\fR\.
.
.TP
\fIGEO\fR
\fIX\fR     Pixel x size specified by an integer\.
.br
\fIY\fR     Pixel y size specified by an integer\.
.br
\fIW\fR     Pixel width size specified by an integer\.
.br
\fIH\fR     Pixel height size specified by an integer\.
.br
\fIPRO\fR   Procent size specified by an integer\.
.br
\fI\-\fR     Means, that old size is kept\.
.br
Samples: \fB<X>,<Y>\fR, \fB<W>,<H>\fR, \fB<PRO>,<PRO>\fR, \fB<PRO>\fR
.
.SH "EXAMPLES"
.
.TP
To move windows:
xwinpp \-F \./list \-p | xwinmo \- \-m \-V \-e px \-g 640,800
.br
xwinpp \-F \./list \-p | xwinmo \- \-m \-e pro \-R workarea \-g 50,\-
.br
xwinpp \-F \./list \-p | xwinmo \- \-m \-e pro \-R window \-g 100 \-d east
.br
xwinpp \-F \./list \-p | xwinmo \- \-M \-W \-D 1
.br
xwinpp \-F \./list \-s \-D 1 \-p | xwinmo \- \-M \-D curr
.
.SH "RETURN VALUES"
.
.TP
1
USAGE: xwinmo (\-|\-F|\-h|\-v) [\-wx|\-wy|\-ww|\-wh] (\-c|\-f|\-H|\-M|\-m|\-U|\-s)
.
.TP
2
There is no window in list\.
.
.TP
3
No action spezified\.
.
.SH "NOTES"
.
.IP "\(bu" 4
You may write all commands and options without masking \fB\-\fR\. So, instead of \fB\-help\fR you may use \fBhelp\fR\.
.
.IP "\(bu" 4
If no workarea geo is set, \fBxwinmo\fR uses \fB_NET_WORKAREA\fR\.
.
.IP "" 0
.
.SH "CONFIGURATION"
Instead options \fB\-wx\fR, \fB\-wy\fR, \fB\-ww\fR and \fB\-wh\fR you may set these variables in the first section of the script\.
.
.SH "BUGS & REQUESTS"
Report it on \fB<https://github\.com/D630/xwinmo>\fR
.
.SH "TODO"
.
.IP "\(bu" 4
Provide a "professional" error handling\.
.
.IP "\(bu" 4
Correct the English in this manpage\.
.
.IP "" 0
.
.SH "LICENSE"
\fBxwinmo\fR is licensed with \fBGNU GPLv3\fR\. You should have received a copy of the \fBGNU General Public License\fR along with this program\. If not, see for more details \fB<http://www\.gnu\.org/licenses/gpl\-3\.0\.html>\fR
.
.SH "CHRONOLOGY"
First version (\fB0\.1\.0\.0\fR) was finished on 10\. February 2014\.
.
.SH "SEE ALSO"
\fBbash\fR(1), \fBwmctrl\fR(1), \fBx\fR(7), \fBxprop\fR(1), \fBxwinpp\fR(1)
